@url=http://localhost:3000

### Lista de todas las tareas
GET {{url}}/tareas

### Crear tarea 1
POST {{url}}/tareas
Content-Type: application/json

{
  "nombre": "Aprender Node",
  "completada": false
}

### Crear tarea 2
POST {{url}}/tareas
Content-Type: application/json

{
  "nombre": "Escribir documentación",
  "completada": true
}

### Lista completadas
GET {{url}}/tareas?completada=true

### Lista no completadas
GET {{url}}/tareas?completada=false

### Consultar  por índice 
GET {{url}}/tareas/0

### Consultar  por índice 
GET {{url}}/tareas/1