@url=http://localhost:3000

### Crear alumno
POST {{url}}/alumnos
Content-Type: application/json

{
  "nombre": "Micaela",
  "nota1": 4,
  "nota2": 5,
  "nota3": 6
}

### Crear otro alumno
POST {{url}}/alumnos
Content-Type: application/json

{
  "nombre": "Julian",
  "nota1": 8,
  "nota2": 9,
  "nota3": 10
}

### todos los alumnos
GET {{url}}/alumnos

### Consultar un alumno por ID
GET {{url}}/alumnos/1

### Modificar un alumno por ID
PUT {{url}}/alumnos/2
Content-Type: application/json

{
  "nombre": "Ariel",
  "nota1": 6,
  "nota2": 7,
  "nota3": 5
}